<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

// This file handles pages, but only exists for the sake of child theme forward compatibility.
/*remove_action( 'genesis_loop', 'genesis_do_loop' );
add_action( 'genesis_after_header', 'paradoja_404_container' );
function paradoja_404_container(){
	echo '<div class="sec-prof wrapper-paradoja">';
		echo '<h1>404 Not Found</h1>';
	echo '</div>';
}
*/
genesis();
