<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

// This file handles pages, but only exists for the sake of child theme forward compatibility.
/*remove_action( 'genesis_loop', 'genesis_do_loop' );
add_action( 'genesis_after_header', 'paradoja_single_container' );
function paradoja_single_container(){
	echo '<div class="sec-prof wrapper-paradoja">';
		echo '<div class="container" style="padding-left:0;padding-right:0;">';
			echo '<div class="hero-project"><img src="'.get_field('project_banner').'"><h1>'.get_the_title().'</h1></div>';
			echo '<div class="project-content">'.get_post_field('post_content', get_the_ID()).'</div>';
			$images = get_field('gallery');
			if( $images ):
				echo '<div class="gallery-project">';
				$counter = 0;
				$counter2 = 0;
				$total = count($images);
				foreach( $images as $image ):
					$counter++;
					$counter2++;
					if ($counter == 2) {
						echo '<div class="two-galleries">';
					}
					echo '<div class="gallery-item item-'.$counter.'"><a href="'.wp_get_attachment_image_url( $image['ID'], 'full' ).'">'.wp_get_attachment_image( $image['ID'], 'full' ).'</a></div>';
					if ($counter2 == $total && $counter == 2) {
						echo '</div>';
					}
					if ($counter == 3) {
						$counter = 0;
						echo '</div>';
					}
				endforeach;
				echo '</div>';
			endif;
		echo '</div>';
	echo '</div>';
}*/

genesis();
